acme_project/acme_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Если на сервер пришёл запрос к главной странице,
    # Django проверит на совпадение с запрошенным URL 
    # все path() в файле urls.py приложения homepage.
    path('', include('homepage.urls')),
    
    # Если в приложении homepage не найдётся совпадений,
    # Django продолжит искать совпадения здесь, в корневом файле urls.py.

    # Если запрос начинается с catalog/, 
    # Django будет искать совпадения в файле urls.py
    # приложения catalog.
    path('catalog/', include('catalog.urls'))
]

acme_project/catalog/urls.py
# catalog/urls.py
from django.urls import path

from . import views

# Указываем namespace для ссылок приложения:
app_name = 'catalog'

urlpatterns = [
    # Если пришёл запрос к относительному URL catalog/,
    # то запрос из корневого urls.py перенаправляется сюда, 
    # в файл catalog/urls.py;
    # и если в запросе после 'catalog/' ничего нет (пустая строка),
    # будет вызвана view-функция product_list() из файла catalog/views.py
    path('', views.product_list, name='product_list'),
    
    # Если в запросе после 'catalog/' стоит '1/' или '2/',
    # будет вызвана view-функция product_detail() из файла catalog/views.py
    
    # Имя для URL лучше задавать такое же, как и имя функции. 
    # Легко запомнить, просто понять:
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('<slug:category>/', views.product_category),
    
]

acme_project/homepage/urls.py
# homepage/urls.py
# Импортируем функцию path() 
# и файл homepage/views.py, в котором объявлена view-функция index().

from django.urls import path

from . import views


urlpatterns = [
    # Если вызван URL без относительного адреса (шаблон — пустые кавычки),
    # то вызывается view-функция index() из файла views.py
    path('', views.index),
    
]

acme_project/catalog/models.py
from django.db import models

# Create your models here.

acme_project/homepage/models.py
from django.db import models

# Create your models here.

acme_project/catalog/views.py
from django.shortcuts import render

from django.http import HttpResponse

# Create your views here.
def product_category(request, category):
    return HttpResponse(f'Категория {category}')

def product_list(request):
    template_name = 'catalog/product_list.html'
    title = 'Список товаров ACME'
    products = [
        'Iron carrot',
        'Giant mousetrap',  
        'Dehydrated boulders',
        'Invisible paint',
    ]
    context = {
        'title': title,
        'products': products,
    }
    return render(request, template_name, context)

def product_detail(request, pk):
    return HttpResponse('Its dummy response {pk=}')

acme_project/homepage/views.py
from django.shortcuts import render

from django.http import HttpResponse

# Create your views here.
def index(request):
    # Адрес шаблона сохранён в переменную, это не обязательно, но удобно.
    template_name = 'homepage/index.html'
    # Строка, которую надо вывести на страницу, тоже сохранена в переменную.
    title = 'Главная страница ACME'
    promo_product ='Iron carrot'
    context ={
        # Ключ словаря и имя переменной не обязательно называть одинаково,
        # но обычно это удобнее, чем использовать два разных имени.
        'title': title,
        'promo_product': promo_product
    }
    # Третьим аргументом в render() передаём словарь context:
    return render(request, template_name=template_name, context=context)

acme_project/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>
            {% block title %}
            {% endblock %}
        </title>
    </head>

    <body>
        {% include 'includes/header.html' %}
        <main>
            {% block content %}
                Контента пока нет
            {% endblock %}
        </main>
        {% include 'includes/footer.html' %}
    </body>

</html>

acme_project/templates/catalog/catalog.html
{% extends 'base.html' %}

{% block content %}
    <p>Content from catalog.html</p>
{% endblock %}

acme_project/templates/catalog/product_list.html
{% extends 'base.html' %}

{% block title %}
    титульник product_list-a
{% endblock %}

{% block content %}
    <p>Content from product_list.html</p>
    <h1>{{ title }}</h1>
    <!--
        список можно перебрать циклом {% for ... in ... %}
        в шаблоне обязателен закрывающий тег {% endfor %}.
    -->
    {% for product in products %}
        <p>{{ product }}</p>
        <!--
        В циклах, применяемых в шаблонах Django, доступна переменная forloop — объект с несколькими полезными атрибутами
        -->
        {% if forloop.last %}
            <hr>
        {% endif %}
    <!--
        В циклах шаблонов можно применить необязательный одиночный тег  empty ; его ставят перед закрывающим тегом  endfor . Если коллекция, переданная в цикл, пуста, будет выведено содержимое, размещённое между  empty  и  endfor . 
    -->
    {% empty %}
        <p>Товаров пока нет</p>
    {% endfor %}
{% endblock %}

acme_project/templates/homepage/index.html
{% extends 'base.html' %}

{% block title %}
    <h1>это титульник {{ title }}</h1>
{% endblock %}

{% block content %}
    <p>Это Контент из index.html</p>
    <a href="{% url 'catalog:product_list' %}">
        Страница со списком товаров
    </a>
    <!--
        {{ var_dict.key }} — обращение к ключу вложенного словаря
        {{ var_instance.attribute }} — обращение к атрибуту или методу класса
        {{ var_list.0 }} — обращение к элементу списка 
    -->
    <p>
    {% if promo_product == "Iron carrot" %}
        Железная морковка — хорошо для стальных зубов.
    {% elif promo_product == "Giant mousetrap" %}
        Ребята, давайте жить дружно!
    {% else %}
        Вы все меня ещё не знаете, но вы меня узнаете!
    {% endif %}
    </p>
    <p>Товар дня: {{ promo_product }}</p>
    {% lorem 1 p %}
{% endblock %}

acme_project/templates/includes/footer.html
<footer>
    <p>Копирайт, год создания</p>
</footer>

acme_project/templates/includes/header.html
<header>
    <p>Место для логотипа</p>
    <nav>Навигация</nav>
</header>